### ISSUE TITLE
Issue with State-Sync

### ISSUE THREAD

**Issue by hard-nett** [terpnetwork/terp-core#134]
#### Specifications

Terp-Core version: `v2.0.0`
OS & Version: Windows/Linux/OSX
Commit hash:  v2.0.0

#### Actual behavior
errors

#### Steps to reproduce the behavior
SImple attempt to state-synce to node

#### Backtrace

````
8:17PM INF starting node with ABCI Tendermint in-process module=server
8:17PM INF service start impl=multiAppConn module=proxy msg={}
8:17PM INF service start connection=query impl=localClient module=abci-client msg={}
8:17PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
8:17PM INF service start connection=mempool impl=localClient module=abci-client msg={}
8:17PM INF service start connection=consensus impl=localClient module=abci-client msg={}
8:17PM INF service start impl=EventBus module=events msg={}
8:17PM INF service start impl=PubSub module=pubsub msg={}
8:17PM INF service start impl=IndexerService module=txindex msg={}
8:17PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=2.0.0
8:17PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
8:17PM INF InitChain chainID=90u-2 initialHeight=1 module=server
8:17PM INF initializing blockchain state from genesis.json module=server
8:17PM INF asserting crisis invariants inv=1/13 module=x/crisis name=bank/nonnegative-outstanding
8:17PM INF asserting crisis invariants inv=2/13 module=x/crisis name=bank/total-supply
8:17PM INF asserting crisis invariants inv=3/13 module=x/crisis name=gov/module-account
8:17PM INF asserting crisis invariants inv=4/13 module=x/crisis name=transfer/total-escrow-per-denom
8:17PM INF asserting crisis invariants inv=5/13 module=x/crisis name=group/Group-TotalWeight
8:17PM INF asserting crisis invariants inv=6/13 module=x/crisis name=staking/module-accounts
8:17PM INF asserting crisis invariants inv=7/13 module=x/crisis name=staking/nonnegative-power
8:17PM INF asserting crisis invariants inv=8/13 module=x/crisis name=staking/positive-delegation
8:17PM INF asserting crisis invariants inv=9/13 module=x/crisis name=staking/delegator-shares
8:17PM INF asserting crisis invariants inv=10/13 module=x/crisis name=distribution/nonnegative-outstanding
8:17PM INF asserting crisis invariants inv=11/13 module=x/crisis name=distribution/can-withdraw
8:17PM INF asserting crisis invariants inv=12/13 module=x/crisis name=distribution/reference-count
8:17PM INF asserting crisis invariants inv=13/13 module=x/crisis name=distribution/module-account
8:17PM INF asserted all invariants duration=6.54281 height=0 module=x/crisis
8:17PM INF created new capability module=ibc name=ports/transfer
8:17PM INF port binded module=x/ibc/port port=transfer
8:17PM INF claimed capability capability=1 module=transfer name=ports/transfer
8:17PM INF created new capability module=ibc name=ports/icahost
8:17PM INF port binded module=x/ibc/port port=icahost
8:17PM INF claimed capability capability=2 module=icahost name=ports/icahost
panic: unknown field "address" in types.AccessConfig

goroutine 13 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x0?, {0xc00095cf00?, 0xedc4c6a40?, 0x0?}, {0x32b5a50?, 0xc0038d2540?})
        github.com/cosmos/cosmos-sdk@v0.47.4/codec/proto_codec.go:187 +0x3b
github.com/CosmWasm/wasmd/x/wasm.AppModule.InitGenesis({{}, {0x32ef7d8, 0xc0013bfc60}, 0xc000a23b78, {0x32a4920, 0xc000ace3c0}, {0x32b3fa0, 0xc00017ce60}, {0x32af730, 0xc000fc1e40}, ...}, ...)
        github.com/CosmWasm/wasmd@v0.41.0/x/wasm/module.go:183 +0x94
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x32cf230, 0x48cdec0}, {0x32e4310, 0xc0012d8880}, {{0x0, 0x0}, {0xc0027e22e8, 0x5}, 0x0, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.47.4/types/module/module.go:357 +0x373
github.com/terpnetwork/terp-core/v2/app.(*TerpApp).InitChainer(_, {{0x32cf230, 0x48cdec0}, {0x32e4310, 0xc0012d8880}, {{0x0, 0x0}, {0xc0027e22e8, 0x5}, 0x0, ...}, ...}, ...)
        github.com/terpnetwork/terp-core/v2/app/app.go:1170 +0x18f
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000f31e00, {{0x0, 0xedc4c6a40, 0x0}, {0xc0027e22e8, 0x5}, 0xc000b3eac0, {0x48cdec0, 0x0, 0x0}, ...})
        github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/abci.go:78 +0x515
github.com/cometbft/cometbft/abci/client.(*localClient).InitChainSync(0xc000142ea0, {{0x0, 0xedc4c6a40, 0x0}, {0xc0027e22e8, 0x5}, 0xc000b3eac0, {0x48cdec0, 0x0, 0x0}, ...})
        github.com/cometbft/cometbft@v0.37.2/abci/client/local_client.go:275 +0x102
github.com/cometbft/cometbft/proxy.(*appConnConsensus).InitChainSync(0xc0016376b0, {{0x0, 0xedc4c6a40, 0x0}, {0xc0027e22e8, 0x5}, 0xc000b3eac0, {0x48cdec0, 0x0, 0x0}, ...})
        github.com/cometbft/cometbft@v0.37.2/proxy/app_conn.go:85 +0x198
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x26c7314, 0x6}}, {0xc0027e22e8, 0x5}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/cometbft/cometbft@v0.37.2/consensus/replay.go:319 +0xeb8
github.com/cometbft/cometbft/consensus.(*Handshaker).Handshake(0xc00355db68, {0x32e6ad0, 0xc0027f2000})
        github.com/cometbft/cometbft@v0.37.2/consensus/replay.go:268 +0x388
github.com/cometbft/cometbft/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x26c7314, 0x6}}, {0xc0027e22e8, 0x5}, 0x1, 0x0, ...}, ...)
        github.com/cometbft/cometbft@v0.37.2/node/node.go:328 +0x198
github.com/cometbft/cometbft/node.NewNode(0xc00065adc0, {0x32b42e0, 0xc000e20f00}, 0xc00279af20, {0x32a52c0, 0xc0027ab3c8}, 0x1?, 0x48cdec0?, 0xc002c0ea58, {0x32cf6c8, ...}, ...)
        github.com/cometbft/cometbft@v0.37.2/node/node.go:778 +0x554
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x32e5140, 0xc00161d710}, 0x0, {0xc001600c60, 0x5}, {0x32ef7d8, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.47.4/server/start.go:320 +0x797
github.com/cosmos/cosmos-sdk/server.StartCmd.func2.2()
        github.com/cosmos/cosmos-sdk@v0.47.4/server/start.go:151 +0x45
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile.func2()
        github.com/cosmos/cosmos-sdk@v0.47.4/server/start.go:557 +0x22
created by github.com/cosmos/cosmos-sdk/server.wrapCPUProfile in goroutine 1
        github.com/cosmos/cosmos-sdk@v0.47.4/server/start.go:556 +0x22f
````

When submitting logs: please submit them as text and not screenshots.

**Comment by discoverdefiteam** [comment]
is resolved
